# Generated by Django 4.1.3 on 2022-12-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
